-- Eliminar tabla PELICULAS si existe
DROP TABLE PELICULAS;

-- Crear tabla PELICULAS
CREATE TABLE PELICULAS (
ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
TITULO VARCHAR2(255) NOT NULL,
ANIO NUMBER(4) NOT NULL,
DIRECTOR VARCHAR2(255) NOT NULL,
GENERO VARCHAR2(100) NOT NULL,
SINOPSIS VARCHAR2(1000)
);

-- Insertar películas
INSERT INTO PELICULAS (TITULO, ANIO, DIRECTOR, GENERO, SINOPSIS)
VALUES ('Volver al Futuro', 1985, 'Robert Zemeckis', 'Ciencia ficción', 'Un adolescente viaja accidentalmente al pasado en un auto DeLorean y debe asegurarse de que sus padres se enamoren para poder regresar al futuro.');

INSERT INTO PELICULAS (TITULO, ANIO, DIRECTOR, GENERO, SINOPSIS)
VALUES ('Interestelar', 2014, 'Christopher Nolan', 'Ciencia ficción', 'Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.');

INSERT INTO PELICULAS (TITULO, ANIO, DIRECTOR, GENERO, SINOPSIS)
VALUES ('Harry Potter y la Piedra Filosofal', 2001, 'Chris Columbus', 'Fantasía', 'Un joven huérfano descubre que es un mago y es admitido en la escuela de magia y hechicería Hogwarts.');

INSERT INTO PELICULAS (TITULO, ANIO, DIRECTOR, GENERO, SINOPSIS)
VALUES ('Doctor Strange', 2016, 'Scott Derrickson', 'Acción', 'Un brillante neurocirujano descubre el mundo de la magia y las dimensiones alternativas tras sufrir un accidente.');

INSERT INTO PELICULAS (TITULO, ANIO, DIRECTOR, GENERO, SINOPSIS)
VALUES ('El Código Enigma', 2014, 'Morten Tyldum', 'Drama', 'La historia de Alan Turing, el matemático que descifró el código Enigma nazi durante la Segunda Guerra Mundial.');

COMMIT;
